services:
  back:
    image: alvarobustamantecorominas/backend-login-jwt-v1:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - net1
    environment:
       MYSQL_HOST: bd-login
       MYSQL_PORT: 3306
       MYSQL_DB_NAME: login-jwt
       MYSQL_USER: root
       MYSQL_PASSWORD: root
    depends_on:
      - bd-login
    volumes:
      - .m2:/root/.m2

  bd-login:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    networks:
      - net1
    environment:
      MYSQL_DATABASE: login-jwt
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql  # Volume for persistent storage

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: bd-login
    depends_on:
      - bd-login
    networks:
      - net1

  angular-app:
    image: alvarobustamantecorominas/frontend-login-jwt-v1:latest  
    restart: always
    ports:
      - 4200:80  
    networks:
      - net1

networks:
  net1:

volumes:
  mysql-data:  
