services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - net1
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/login-jwt   
    depends_on:
      - mysqldb
    
    volumes:
      - .m2:/root/.m2
      
  mysqldb:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - net1  
    environment:
      MYSQL_DATABASE: login-jwt
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin 
networks:
  net1: