services:
  back:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - net1
    environment:
       MYSQL_HOST: bd-login
       MYSQL_PORT: 3306
       MYSQL_DB_NAME: login-jwt
       MYSQL_USER: root
       MYSQL_PASSWORD: root
    depends_on:
      - bd-login
    volumes:
      - .m2:/root/.m2

  bd-login:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    networks:
      - net1
    environment:
      MYSQL_DATABASE: login-jwt
      MYSQL_ROOT_PASSWORD: root 

networks:
  net1:
